const fs = require('fs');
const path = require('path');

const LOAD_T0 = Date.now(); // TEMP Batch 12: remove with the verification block

const MIN_WORDS = 5;

// ── Load words ──────────────────────────────────────────────────────────────
const raw = fs.readFileSync(path.join(__dirname, 'data', 'dictionary.txt'), 'utf8');
const validWords = new Set(
  raw.split('\n').map(w => w.trim()).filter(w => w.length > 0)
);

// ── Build prompt source pools ───────────────────────────────────────────────
// Prompts are generated by picking a random dictionary word and slicing a
// random substring of the requested length out of it. This guarantees every
// prompt is solvable (the source word itself is a valid answer) and naturally
// weights prompts toward letter combos that occur in many words.
//
// wordsByMinLen[len] = array of words at least `len` characters long, so a
// substring of that length can always be cut from a randomly chosen word.
const wordsByMinLen = { 2: [], 3: [], 4: [] };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length >= len) wordsByMinLen[len].push(word);
  }
}

// Kept for diagnostics / backward compatibility: count of distinct words that
// contain each substring, and the substrings appearing in >= MIN_WORDS words.
const substringCounts = { 2: new Map(), 3: new Map(), 4: new Map() };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length < len) continue;
    const seen = new Set();
    for (let i = 0; i <= word.length - len; i++) {
      const sub = word.slice(i, i + len);
      if (!seen.has(sub)) {
        seen.add(sub);
        substringCounts[len].set(sub, (substringCounts[len].get(sub) || 0) + 1);
      }
    }
  }
}

const playablePrompts = { 2: [], 3: [], 4: [] };
for (const len of [2, 3, 4]) {
  for (const [sub, count] of substringCounts[len]) {
    if (count >= MIN_WORDS) playablePrompts[len].push(sub);
  }
}

// ── Word rarity + scoring (frequency + morphology engine) ────────────────────
// A word's TIER comes from real-world usage frequency (Zipf scale) combined
// with morphological reduction: measured usage wins where it exists, and
// unmeasured words inherit rarity through morphology from whatever they reduce
// to. LEGENDARY is reserved for irreducible words with essentially zero corpus
// presence. Letter difficulty never affects the tier - it feeds the per-word
// SCORE instead (see hardness / getWordScore).
const TIER_NAMES = ['COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'];

// Load the frequency table: tab-separated "word<TAB>zipf", comments start with #.
const wordfreq = new Map(); // word -> Zipf value (log10 occurrences per billion)
{
  const freqRaw = fs.readFileSync(path.join(__dirname, 'data', 'wordfreq-en.txt'), 'utf8');
  for (const line of freqRaw.split('\n')) {
    if (!line || line[0] === '#') continue;
    const tab = line.indexOf('\t');
    if (tab === -1) continue;
    const w = line.slice(0, tab).trim();
    const z = parseFloat(line.slice(tab + 1));
    if (w && Number.isFinite(z)) wordfreq.set(w, z);
  }
}

// Per-letter mechanical difficulty -> hardness(w) in [0,1]. Used only for the
// per-word score, never for the tier.
const LETTER_DIFF = {};
for (const c of 'eaionrtslu') LETTER_DIFF[c] = 0.0;
for (const c of 'dgcmbph')    LETTER_DIFF[c] = 0.30;
for (const c of 'fwyv')       LETTER_DIFF[c] = 0.55;
LETTER_DIFF['k'] = 0.75;
for (const c of 'jx')         LETTER_DIFF[c] = 0.90;
for (const c of 'qz')         LETTER_DIFF[c] = 1.0;
const VOWELS = new Set(['a','e','i','o','u']);
function hardness(w) {
  if (!w) return 0;
  let s = 0; for (const c of w) s += (LETTER_DIFF[c] ?? 0.4);
  let base = s / w.length, bonus = 0;
  for (let i = 0; i < w.length; i++)
    if (w[i] === 'q' && (i+1 >= w.length || w[i+1] !== 'u')) bonus += 0.15;
  let hasVowel = false; for (const c of w) if (VOWELS.has(c)) hasVowel = true;
  if (!hasVowel && !w.includes('y')) bonus += 0.25;
  return Math.min(1, base + bonus);
}
function zipfOf(w) { return wordfreq.get(w) || 0; }
// The frequency-rarity spine: 0 = everyday word, 1 = unseen in the corpus.
function freqRarity(w) {
  return Math.min(1, Math.max(0, (7.5 - zipfOf(w)) / 7.5));
}

// ── Morphological reduction ──────────────────────────────────────────────────
// A word's rarity is the MINIMUM rarity across itself and everything it can be
// morphologically reduced to (suffix strips, and prefix strips for words the
// corpus never measured), applied recursively: enravished -> enravish ->
// ravish. Measured usage wins where it exists; unmeasured words inherit
// through morphology; LEGENDARY is reserved for irreducible words with
// essentially zero corpus presence. Errors in the reduction rules only ever
// push words DOWN in tier, never up, so the system is stingy by construction.

// Suffix strips, applied to every word: [suffix, replacement].
const SUFFIX_RULES = [
  ['ies', 'y'], ['es', ''], ['s', ''],
  ['ed', ''], ['ed', 'e'],
  ['ing', ''], ['ing', 'e'], ['ings', ''], ['ings', 'e'],
  ['er', ''], ['er', 'e'], ['ers', ''], ['ers', 'e'],
  ['est', ''], ['est', 'e'], ['iest', 'y'], ['ier', 'y'],
  ['ily', 'y'], ['ly', ''], ['ally', ''],
  ['ness', ''], ['iness', 'y'], ['less', ''], ['ful', ''],
  ['ment', ''], ['ments', ''],
  ['ation', 'ate'], ['ations', 'ate'],
  ['isation', 'ise'], ['ization', 'ize'], ['isations', 'ise'], ['izations', 'ize'],
  ['ize', 'e'], ['ize', ''], ['ise', 'e'], ['ise', ''],
  ['ism', ''], ['isms', ''], ['ist', ''], ['ists', ''],
];
// Bare strips that get a doubled-consonant retry: perilling -> perill fails,
// so also try peril.
const DOUBLED_RETRY = new Set(['ing', 'ed', 'er', 'est']);
const VOWEL_SET = new Set(['a', 'e', 'i', 'o', 'u']);

// Prefix strips, applied ONLY when the word itself is absent from wordfreq.
// Prefixes exist to clean the unmeasured junk pile (unmodernized, superactive);
// skipping measured words protects false positives like regale -> gale and
// distend -> tend.
const PREFIXES = [
  'un', 'non', 're', 'de', 'dis', 'mis', 'over', 'under', 'out', 'pre', 'post',
  'anti', 'semi', 'super', 'sub', 'counter', 'fore', 'be', 'en', 'em', 'circum',
  'auto', 'pseudo', 'proto', 'mono', 'poly', 'multi', 'inter', 'intra', 'trans',
  'extra', 'micro', 'macro', 'neo', 'mid', 'co', 'bi', 'tri', 'di',
];

// Valid reduction neighbors of w: stems at least 3 letters, strictly shorter,
// and present in the dictionary.
function reductionNeighbors(w) {
  const out = new Set();
  for (const [suffix, replacement] of SUFFIX_RULES) {
    if (w.length <= suffix.length || !w.endsWith(suffix)) continue;
    const stem = w.slice(0, w.length - suffix.length) + replacement;
    if (stem.length >= 3 && stem.length < w.length && validWords.has(stem)) {
      out.add(stem);
    } else if (replacement === '' && DOUBLED_RETRY.has(suffix) &&
               stem.length >= 4 &&
               stem[stem.length - 1] === stem[stem.length - 2] &&
               !VOWEL_SET.has(stem[stem.length - 1])) {
      const single = stem.slice(0, -1);
      if (single.length >= 3 && single.length < w.length && validWords.has(single)) out.add(single);
    }
  }
  if (!wordfreq.has(w)) {
    for (const p of PREFIXES) {
      if (w.length <= p.length || !w.startsWith(p)) continue;
      const stem = w.slice(p.length);
      if (stem.length >= 3 && stem.length < w.length && validWords.has(stem)) out.add(stem);
    }
  }
  return out;
}

// Tier cuts on the frequency-rarity spine. c4 = 0.827 corresponds to zipf 1.3:
// LEGENDARY needs an irreducible word that is absent from the corpus or
// measured at essentially zero presence.
const TIER_CUTS = { c1: 0.44, c2: 0.60, c3: 0.68, c4: 0.827 };

// Effective rarity: min over the word's own freqRarity and the rarityScore of
// every reduction neighbor, recursively. Reductions strictly shorten words so
// there are no cycles; depth 6 is a safety bound. Memoized: deep chains would
// otherwise recompute exponentially.
const rarityMemo = new Map();
function rarityOf(w, depth) {
  const memo = rarityMemo.get(w);
  if (memo !== undefined) return memo;
  let r = freqRarity(w);
  if (depth < 6) {
    for (const n of reductionNeighbors(w)) {
      const nr = rarityOf(n, depth + 1);
      if (nr < r) r = nr;
    }
  }
  rarityMemo.set(w, r);
  return r;
}
function rarityScore(word) {
  return rarityOf(String(word).trim().toLowerCase(), 0);
}
function getWordTier(word) {
  const s = rarityScore(word);
  return s < TIER_CUTS.c1 ? 'COMMON'
       : s < TIER_CUTS.c2 ? 'UNCOMMON'
       : s < TIER_CUTS.c3 ? 'RARE'
       : s < TIER_CUTS.c4 ? 'EPIC'
       : 'LEGENDARY';
}
// Transparent per-word score: tier base + length reward + letter hardness
// (speed bonus added by the caller). Hard letters pay here, not in the tier,
// so zyzzyva out-points same-tier easy-lettered words.
const TIER_BASE = { COMMON: 1.0, UNCOMMON: 1.6, RARE: 2.6, EPIC: 4.0, LEGENDARY: 6.0 };
function getWordScore(word) {
  const w = String(word).trim().toLowerCase();
  const tier = getWordTier(w);
  const lengthPts = 2 * Math.max(0, w.length - 3);
  return Math.round(10 * TIER_BASE[tier] + lengthPts + 6 * hardness(w));
}

// ── Daily challenge prompt pools (Feature 8) ─────────────────────────────────
// Bucket each length's playable substrings by how many distinct words contain
// them. High count = many solutions = easy; low count = few solutions = hard
// (but still solvable, since the pool is the >= MIN_WORDS playable set).
function bucketByCount(len) {
  const arr = playablePrompts[len].map(s => [s, substringCounts[len].get(s) || 0]);
  arr.sort((a, b) => a[1] - b[1]); // ascending: rare → common
  const n = arr.length;
  const third = Math.floor(n / 3);
  return {
    rare:   arr.slice(0, third).map(x => x[0]),
    mid:    arr.slice(third, 2 * third).map(x => x[0]),
    common: arr.slice(2 * third).map(x => x[0]),
  };
}
const _b2 = bucketByCount(2), _b3 = bucketByCount(3), _b4 = bucketByCount(4);
const dailyPools = {
  common2: _b2.common,            // easy: common 2-letter clusters
  mid3:    _b3.mid,               // medium: mid-rarity 3-letter clusters
  rare34:  _b3.rare.concat(_b4.rare), // hard: rare 3/4-letter clusters
};

// ── Practice difficulty pools ────────────────────────────────────────────────
// The solution-count map is substringCounts above (every distinct substring of
// lengths 2-4 across the dictionary, counted once per containing word). The
// practice pools reuse the daily's solvability thirds: easy = the
// most-solvable third, hard = the least-solvable third (already floored at
// MIN_WORDS solutions by the playable set). Medium is NOT a pool: it is the
// existing generatePrompt path, completely unchanged.
const practicePools = {
  easy: { 2: _b2.common, 3: _b3.common, 4: _b4.common },
  hard: { 2: _b2.rare, 3: _b3.rare, 4: _b4.rare },
};

// How many dictionary words contain this substring.
function solutionCount(sub) {
  const s = String(sub).toLowerCase();
  const m = substringCounts[s.length];
  return m ? (m.get(s) || 0) : 0;
}

// A practice prompt of the given length and difficulty, avoiding prompts
// already used this session until the pool is effectively exhausted.
function generatePracticePrompt(length, difficulty, usedPrompts) {
  const pool = practicePools[difficulty] && practicePools[difficulty][length];
  let p, guard = 0;
  do {
    p = pool ? pool[Math.floor(Math.random() * pool.length)] : generatePrompt(length);
    guard++;
  } while (usedPrompts && usedPrompts.has(p) && guard < 200);
  return p;
}

// The cheapest ways out of a prompt: up to `limit` valid words containing it,
// excluding words already used this session, sorted by score ascending (most
// common and cheapest first). Used for the practice "what killed you" recap.
function easiestAnswersFor(prompt, usedWords, limit = 3) {
  const matches = [];
  for (const w of wordsByMinLen[2]) {
    if (w.length < 3 || !w.includes(prompt)) continue;
    if (usedWords && usedWords.has(w)) continue;
    matches.push([w, getWordScore(w)]);
  }
  matches.sort((a, b) => a[1] - b[1]);
  return matches.slice(0, limit).map(([word, score]) => ({ word, score, tier: getWordTier(word) }));
}

// Deterministic PRNG so a given day yields the same sequence for everyone.
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Builds the 30-prompt daily gauntlet for a given YYYYMMDD integer. Difficulty
 * ramps: 1-10 easy 2-letter, 11-20 mid 3-letter, 21-30 rare 3/4-letter.
 */
function generateDailyPrompts(dateInt) {
  const rng = mulberry32(dateInt);
  const used = new Set();
  const draw = (pool) => {
    let p, guard = 0;
    do { p = pool[Math.floor(rng() * pool.length)]; guard++; } while (used.has(p) && guard < 60);
    used.add(p);
    return p;
  };
  const out = [];
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.common2));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.mid3));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.rare34));
  return out;
}

// TEMP Batch 12: remove after review - reduction-engine verification.
{
  const loadMs = Date.now() - LOAD_T0;
  const expect = {
    LEGENDARY: ['zyzzyva', 'zyzzyvas', 'qoph', 'qophs', 'pinguefy', 'sesquipedalian', 'crwth', 'borborygmus', 'mangelwurzel', 'absquatulate'],
    EPIC: ['syzygy', 'zugzwang', 'perspicacious', 'defenestration', 'defenestrations', 'syphilitically', 'mellifluously', 'umlauts', 'regale', 'distend'],
    RARE: ['nefarious', 'nefariously', 'primly', 'tourniquets', 'epsilons', 'superheated', 'telegraphies', 'blithering', 'mustiness'],
    UNCOMMON: ['cretaceously', 'perilling'],
    COMMON: ['the', 'cat', 'quickly', 'happily', 'unmodernized', 'divinise', 'superactive'],
  };
  console.log('TEMP Batch 12 tier verification:');
  let mismatches = 0;
  for (const [want, words] of Object.entries(expect)) {
    for (const w of words) {
      const got = getWordTier(w);
      if (got !== want) mismatches++;
      console.log(`  ${w} -> ${got}${got === want ? '' : ` (EXPECTED ${want})`}`);
    }
  }
  console.log(`  mismatches: ${mismatches}`);

  // Property 1: a word is never rarer than any of its reduction neighbors.
  const TIER_RANK = { COMMON: 0, UNCOMMON: 1, RARE: 2, EPIC: 3, LEGENDARY: 4 };
  const all = [...validWords];
  let checked = 0, violations = 0;
  while (checked < 2000) {
    const w = all[(Math.random() * all.length) | 0];
    const neighbors = reductionNeighbors(w);
    if (!neighbors.size) continue;
    checked++;
    for (const n of neighbors) {
      if (TIER_RANK[getWordTier(w)] > TIER_RANK[getWordTier(n)]) {
        violations++;
        console.log(`  VIOLATION: ${w} (${getWordTier(w)}) rarer than neighbor ${n} (${getWordTier(n)})`);
      }
    }
  }
  console.log(`  property check: ${checked} words with neighbors checked, ${violations} violations`);

  // Property 2: size of the LEGENDARY pool, surface and irreducible.
  const scanT0 = Date.now();
  let legendary = 0, legendaryIrreducible = 0;
  for (const w of validWords) {
    if (getWordTier(w) === 'LEGENDARY') {
      legendary++;
      if (reductionNeighbors(w).size === 0) legendaryIrreducible++;
    }
  }
  console.log(`  LEGENDARY pool: ${legendary} surface forms, ${legendaryIrreducible} irreducible`);
  console.log(`  dictionary load time: ${loadMs}ms, full tier scan: ${Date.now() - scanT0}ms`);
}

// TEMP Batch 13: remove after review - bi/tri/di prefix check.
console.log(`TEMP Batch 13 prefix check: biyearly -> ${getWordTier('biyearly')}, triweekly -> ${getWordTier('triweekly')}`);

// ── Exports ─────────────────────────────────────────────────────────────────

/**
 * Returns a random prompt of the given length (2, 3, or 4) by choosing a random
 * dictionary word and slicing a random substring of that length out of it.
 */
function generatePrompt(length) {
  const pool = wordsByMinLen[length];
  const word = pool[Math.floor(Math.random() * pool.length)];
  const start = Math.floor(Math.random() * (word.length - length + 1));
  return word.slice(start, start + length);
}

/**
 * A valid dictionary word containing `prompt`, for the informational
 * "e.g. WORD" flash after a timeout. Random probes give an unbiased pick for
 * common substrings; rare ones fall back to a capped scan. Words already used
 * this game are skipped when possible.
 */
function exampleWordFor(prompt, usedWords) {
  const pool = wordsByMinLen[2]; // effectively the whole dictionary, as an array
  for (let i = 0; i < 1500; i++) {
    const w = pool[(Math.random() * pool.length) | 0];
    if (w.length >= 3 && w.includes(prompt) && !(usedWords && usedWords.has(w))) return w;
  }
  const matches = [];
  for (const w of pool) {
    if (w.length < 3 || !w.includes(prompt)) continue;
    if (usedWords && usedWords.has(w)) continue;
    matches.push(w);
    if (matches.length >= 400) break;
  }
  return matches.length ? matches[(Math.random() * matches.length) | 0] : null;
}

/**
 * Validates a word submission against the current prompt and used-word set.
 * Does NOT modify usedWords — caller adds the word after a successful play.
 *
 * Returns { valid: true } or { valid: false, reason: "..." }.
 */
function isValidWord(word, prompt, usedWords) {
  const w = word.trim().toLowerCase();
  if (!w.includes(prompt)) {
    return { valid: false, reason: `Word must contain "${prompt}".` };
  }
  if (!validWords.has(w)) {
    return { valid: false, reason: `"${w}" is not in the dictionary.` };
  }
  if (w.length < 3) {
    return { valid: false, reason: 'Word must be at least 3 letters long.' };
  }
  if (usedWords.has(w)) {
    return { valid: false, reason: `"${w}" has already been used.` };
  }
  return { valid: true };
}

module.exports = {
  validWords,
  wordsByMinLen,
  substringCounts,
  playablePrompts,
  generatePrompt,
  generatePracticePrompt,
  solutionCount,
  easiestAnswersFor,
  exampleWordFor,
  isValidWord,
  getWordTier,
  getWordScore,
  rarityScore,
  TIER_NAMES,
  generateDailyPrompts,
};
