const fs = require('fs');
const path = require('path');

const LOAD_T0 = Date.now(); // TEMP Batch 12: remove with the verification block

const MIN_WORDS = 5;

// ── Load words ──────────────────────────────────────────────────────────────
const raw = fs.readFileSync(path.join(__dirname, 'data', 'dictionary.txt'), 'utf8');
const validWords = new Set(
  raw.split('\n').map(w => w.trim()).filter(w => w.length > 0)
);

// ── Build prompt source pools ───────────────────────────────────────────────
// Prompts are generated by picking a random dictionary word and slicing a
// random substring of the requested length out of it. This guarantees every
// prompt is solvable (the source word itself is a valid answer) and naturally
// weights prompts toward letter combos that occur in many words.
//
// wordsByMinLen[len] = array of words at least `len` characters long, so a
// substring of that length can always be cut from a randomly chosen word.
const wordsByMinLen = { 2: [], 3: [], 4: [] };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length >= len) wordsByMinLen[len].push(word);
  }
}

// Kept for diagnostics / backward compatibility: count of distinct words that
// contain each substring, and the substrings appearing in >= MIN_WORDS words.
const substringCounts = { 2: new Map(), 3: new Map(), 4: new Map() };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length < len) continue;
    const seen = new Set();
    for (let i = 0; i <= word.length - len; i++) {
      const sub = word.slice(i, i + len);
      if (!seen.has(sub)) {
        seen.add(sub);
        substringCounts[len].set(sub, (substringCounts[len].get(sub) || 0) + 1);
      }
    }
  }
}

const playablePrompts = { 2: [], 3: [], 4: [] };
for (const len of [2, 3, 4]) {
  for (const [sub, count] of substringCounts[len]) {
    if (count >= MIN_WORDS) playablePrompts[len].push(sub);
  }
}

// ── Word rarity + scoring (frequency + morphology engine) ────────────────────
// A word's TIER comes from real-world usage frequency (Zipf scale) combined
// with morphological reduction: measured usage wins where it exists, and
// unmeasured words inherit rarity through morphology from whatever they reduce
// to. LEGENDARY is reserved for irreducible words with essentially zero corpus
// presence. Letter difficulty never affects the tier - it feeds the per-word
// SCORE instead (see hardness / getWordScore).
const TIER_NAMES = ['COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'];

// Per-letter mechanical difficulty -> hardness(w) in [0,1]. Used only for the
// per-word score, never for the tier.
const LETTER_DIFF = {};
for (const c of 'eaionrtslu') LETTER_DIFF[c] = 0.0;
for (const c of 'dgcmbph')    LETTER_DIFF[c] = 0.30;
for (const c of 'fwyv')       LETTER_DIFF[c] = 0.55;
LETTER_DIFF['k'] = 0.75;
for (const c of 'jx')         LETTER_DIFF[c] = 0.90;
for (const c of 'qz')         LETTER_DIFF[c] = 1.0;
const VOWELS = new Set(['a','e','i','o','u']);
function hardness(w) {
  if (!w) return 0;
  let s = 0; for (const c of w) s += (LETTER_DIFF[c] ?? 0.4);
  let base = s / w.length, bonus = 0;
  for (let i = 0; i < w.length; i++)
    if (w[i] === 'q' && (i+1 >= w.length || w[i+1] !== 'u')) bonus += 0.15;
  let hasVowel = false; for (const c of w) if (VOWELS.has(c)) hasVowel = true;
  if (!hasVowel && !w.includes('y')) bonus += 0.25;
  return Math.min(1, base + bonus);
}
// ── Word rarity v2 (batch 50) ────────────────────────────────────────────────
// Rarity and tier are precomputed offline by scripts/build-tiers.js into
// data/tiers-v2.txt ("word<TAB>rarity<TAB>tier"). The engine asks: how likely
// is a player to know this word? Measured corpus frequency where it exists;
// morphological inheritance with per-hop costs where it does not; an n-gram
// English-likeness ranking for the zero-signal residue. See scripts/build-tiers.js
// for the full mechanism and the tier cuts. The TIER is decided at build time
// (full precision) and read verbatim here, so no cut is ever applied at runtime
// and rounding drift across cut boundaries is impossible by construction. The
// rarity column exists only for ordering (rarest-word pick) and display.
// Runtime is a Map lookup. Regenerate the file only when the dictionary, the
// frequency corpus, or the engine itself changes.
const rarityV2 = new Map();
const tierV2 = new Map();
{
  const raw = fs.readFileSync(path.join(__dirname, 'data', 'tiers-v2.txt'), 'utf8');
  for (const line of raw.split('\n')) {
    if (!line) continue;
    const [w, r, t] = line.split('\t');
    rarityV2.set(w, parseFloat(r));
    tierV2.set(w, t);
  }
}
function rarityScore(word) {
  const r = rarityV2.get(String(word).trim().toLowerCase());
  return r == null ? 1 : r; // non-dictionary input grades as alien
}
function getWordTier(word) {
  return tierV2.get(String(word).trim().toLowerCase()) || 'LEGENDARY'; // non-dict input grades alien
}
// Transparent per-word score: tier base + length reward + letter hardness
// (speed bonus added by the caller). Hard letters pay here, not in the tier,
// so zyzzyva out-points same-tier easy-lettered words.
const TIER_BASE = { COMMON: 1.0, UNCOMMON: 1.6, RARE: 2.6, EPIC: 4.0, LEGENDARY: 6.0 };
function getWordScore(word) {
  const w = String(word).trim().toLowerCase();
  const tier = getWordTier(w);
  const lengthPts = 2 * Math.max(0, w.length - 3);
  return Math.round(10 * TIER_BASE[tier] + lengthPts + 6 * hardness(w));
}

// ── Daily challenge prompt pools (Feature 8) ─────────────────────────────────
// Bucket each length's playable substrings by how many distinct words contain
// them. High count = many solutions = easy; low count = few solutions = hard
// (but still solvable, since the pool is the >= MIN_WORDS playable set).
function bucketByCount(len) {
  const arr = playablePrompts[len].map(s => [s, substringCounts[len].get(s) || 0]);
  arr.sort((a, b) => a[1] - b[1]); // ascending: rare → common
  const n = arr.length;
  const third = Math.floor(n / 3);
  return {
    rare:   arr.slice(0, third).map(x => x[0]),
    mid:    arr.slice(third, 2 * third).map(x => x[0]),
    common: arr.slice(2 * third).map(x => x[0]),
  };
}
const _b2 = bucketByCount(2), _b3 = bucketByCount(3), _b4 = bucketByCount(4);
const dailyPools = {
  common2: _b2.common,            // easy: common 2-letter clusters
  mid3:    _b3.mid,               // medium: mid-rarity 3-letter clusters
  rare34:  _b3.rare.concat(_b4.rare), // hard: rare 3/4-letter clusters
};

// ── Practice difficulty pools ────────────────────────────────────────────────
// The solution-count map is substringCounts above (every distinct substring of
// lengths 2-4 across the dictionary, counted once per containing word). The
// practice pools reuse the daily's solvability thirds: easy = the
// most-solvable third, hard = the least-solvable third (already floored at
// MIN_WORDS solutions by the playable set). Medium is NOT a pool: it is the
// existing generatePrompt path, completely unchanged.
const practicePools = {
  easy: { 2: _b2.common, 3: _b3.common, 4: _b4.common },
  hard: { 2: _b2.rare, 3: _b3.rare, 4: _b4.rare },
};

// How many dictionary words contain this substring.
function solutionCount(sub) {
  const s = String(sub).toLowerCase();
  const m = substringCounts[s.length];
  return m ? (m.get(s) || 0) : 0;
}

// A practice prompt of the given length and difficulty, avoiding prompts
// already used this session until the pool is effectively exhausted.
function generatePracticePrompt(length, difficulty, usedPrompts) {
  const pool = practicePools[difficulty] && practicePools[difficulty][length];
  let p, guard = 0;
  do {
    p = pool ? pool[Math.floor(Math.random() * pool.length)] : generatePrompt(length);
    guard++;
  } while (usedPrompts && usedPrompts.has(p) && guard < 200);
  return p;
}

// The practice "what killed you" picks: the single cheapest answer by score,
// plus four words drawn uniformly at random from the non-LEGENDARY candidates
// (legendary words are trophies - the game never gives them away). Excludes
// words already used this session. Order: cheapest first, then the four
// random picks sorted by score ascending. Returns fewer entries when the
// candidate pool runs short.
function killerAnswersFor(prompt, usedWords) {
  const candidates = [];
  for (const w of wordsByMinLen[2]) {
    if (w.length < 3 || !w.includes(prompt)) continue;
    if (usedWords && usedWords.has(w)) continue;
    candidates.push(w);
  }
  if (!candidates.length) return [];
  let cheapest = null, cheapestScore = Infinity;
  for (const w of candidates) {
    const sc = getWordScore(w);
    if (sc < cheapestScore) { cheapestScore = sc; cheapest = w; }
  }
  const pool = candidates.filter(w => w !== cheapest && getWordTier(w) !== 'LEGENDARY');
  const picks = [];
  for (let i = 0; i < 4 && pool.length; i++) {
    const j = Math.floor(Math.random() * pool.length);
    picks.push(pool[j]);
    pool.splice(j, 1);
  }
  picks.sort((a, b) => getWordScore(a) - getWordScore(b));
  const out = [{ word: cheapest, score: cheapestScore, tier: getWordTier(cheapest) }];
  for (const w of picks) out.push({ word: w, score: getWordScore(w), tier: getWordTier(w) });
  return out;
}

// Letter baseline: each letter's share of every letter across the whole
// dictionary. The practice postgame heatmap compares a player's letter usage
// against this to show which letters they lean on.
const letterBaseline = {};
{
  const counts = {};
  let total = 0;
  for (const w of validWords) {
    for (const ch of w) {
      if (ch >= 'a' && ch <= 'z') { counts[ch] = (counts[ch] || 0) + 1; total++; }
    }
  }
  for (let c = 97; c <= 122; c++) {
    const ch = String.fromCharCode(c);
    letterBaseline[ch] = total ? (counts[ch] || 0) / total : 0;
  }
}

// Deterministic PRNG so a given day yields the same sequence for everyone.
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Builds the 30-prompt daily gauntlet for a given YYYYMMDD integer. Difficulty
 * ramps: 1-10 easy 2-letter, 11-20 mid 3-letter, 21-30 rare 3/4-letter.
 */
function generateDailyPrompts(dateInt) {
  const rng = mulberry32(dateInt);
  const used = new Set();
  const draw = (pool) => {
    let p, guard = 0;
    do { p = pool[Math.floor(rng() * pool.length)]; guard++; } while (used.has(p) && guard < 60);
    used.add(p);
    return p;
  };
  const out = [];
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.common2));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.mid3));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.rare34));
  return out;
}

// TEMP Batch 50: remove after review - v2 tier canon + full-distribution check.
{
  const loadMs = Date.now() - LOAD_T0;
  // Canon: [word, expected tier] on the v2 spine (rarity printed alongside).
  const canon = [
    ['happily', 'COMMON'], ['cretaceously', 'RARE'], ['nefariously', 'RARE'],
    ['perspicacious', 'EPIC'], ['cannoli', 'RARE'], ['shipwright', 'RARE'],
    ['chirurgical', 'EPIC'], ['heroon', 'UNCOMMON'], ['pesticidal', 'RARE'],
    ['deific', 'EPIC'], ['fantasmal', 'EPIC'], ['varicosity', 'EPIC'],
    ['turgidities', 'EPIC'], ['hemophilic', 'EPIC'], ['decillions', 'EPIC'],
    ['spaghettini', 'EPIC'], ['pinguefy', 'EPIC'], ['sesquipedalian', 'EPIC'],
    ['absquatulate', 'EPIC'], ['antidisestablishmentarianism', 'EPIC'],
    ['zyzzyva', 'LEGENDARY'], ['borborygmus', 'LEGENDARY'], ['crwth', 'LEGENDARY'],
    ['qoph', 'LEGENDARY'],
  ];
  console.log('TEMP Batch 50 tier verification:');
  let mismatches = 0;
  for (const [w, want] of canon) {
    const got = getWordTier(w);
    if (got !== want) mismatches++;
    console.log(`  ${w.padEnd(30)} -> ${got.padEnd(10)} (rarity ${rarityScore(w).toFixed(4)})${got === want ? '' : ` EXPECTED ${want}`}`);
  }
  console.log(`  mismatches: ${mismatches}`);

  // The full-dictionary distribution must equal the build script's counts.
  const EXPECT_DIST = { COMMON: 21220, UNCOMMON: 60193, RARE: 67479, EPIC: 119808, LEGENDARY: 4511 };
  const counts = {};
  for (const w of validWords) counts[getWordTier(w)] = (counts[getWordTier(w)] || 0) + 1;
  const distOk = TIER_NAMES.every(t => (counts[t] || 0) === EXPECT_DIST[t]);
  console.log(`  distribution: ${JSON.stringify(counts)} ${distOk ? 'OK' : 'MISMATCH vs ' + JSON.stringify(EXPECT_DIST)}`);
  console.log(`  dictionary load time: ${loadMs}ms`);
}

// ── Exports ─────────────────────────────────────────────────────────────────

/**
 * Returns a random prompt of the given length (2, 3, or 4) by choosing a random
 * dictionary word and slicing a random substring of that length out of it.
 */
function generatePrompt(length) {
  const pool = wordsByMinLen[length];
  const word = pool[Math.floor(Math.random() * pool.length)];
  const start = Math.floor(Math.random() * (word.length - length + 1));
  return word.slice(start, start + length);
}

// ── Sabotage: restriction-aware prompt generation ────────────────────────────
// In sabotage, a submitted word disables its distinct letters for the
// opponent's next turn. Prompts must stay solvable under whatever letters are
// currently disabled, so we count prompt-length substrings ONLY across words
// that are themselves legal (long enough, and containing no disabled letter):
// any such word is a valid answer, which keeps the prompt solvable by
// construction. A single O(dictionary) pass per restricted turn (measured
// 7-160ms); no global precompute.

// Distinct prompt-length substring counts over the legal pool (each substring
// counts at most once per word). Internal; shared by the two exports below.
function _sabotageCounts(disabledSet, promptLen) {
  const counts = new Map();
  let legalWords = 0;
  outer: for (const word of validWords) {
    if (word.length < promptLen) continue;
    for (let i = 0; i < word.length; i++) {
      if (disabledSet.has(word[i])) continue outer;
    }
    legalWords++;
    const seen = new Set();
    for (let i = 0; i <= word.length - promptLen; i++) {
      const sub = word.slice(i, i + promptLen);
      if (!seen.has(sub)) { seen.add(sub); counts.set(sub, (counts.get(sub) || 0) + 1); }
    }
  }
  return { counts, legalWords };
}

// The floor cascade over a counts map: prefer richer substrings first,
// appearing in >= 25 legal words, then >= 10, >= 5, >= 3, and finally >= 1.
// Returns { pool, floor } (floor null when nothing legal exists at all).
function _sabotageFloor(counts) {
  for (const floor of [25, 10, 5, 3, 1]) {
    const pool = [];
    for (const [sub, c] of counts) if (c >= floor) pool.push(sub);
    if (pool.length) return { pool, floor };
  }
  return { pool: [], floor: null };
}

/**
 * Diagnostic stats for the legal prompt pool under a disabled-letter set.
 * disabledSet: Set of lowercase single letters. promptLen: 2, 3, or 4.
 * Returns { legalWords, richPrompts, floor }: the legal-word count, the pool
 * size at the floor actually used, and that floor (null when legalWords is 0).
 */
function sabotageLegalStats(disabledSet, promptLen) {
  const { counts, legalWords } = _sabotageCounts(disabledSet, promptLen);
  if (legalWords === 0) return { legalWords: 0, richPrompts: 0, floor: null };
  const { pool, floor } = _sabotageFloor(counts);
  return { legalWords, richPrompts: pool.length, floor };
}

/**
 * A prompt that stays solvable under the current disabled-letter set.
 * Empty set: the untouched classic path. Otherwise a uniform random member of
 * the floor-cascaded legal pool at promptLen; if there are zero legal words at
 * promptLen, cascade the length down (promptLen-1, then 2). If still nothing,
 * fall back to an unrestricted prompt: the opponent is fully locked out and
 * will lose the life (deliberate, no cap or mitigation).
 */
function generateSabotagePrompt(promptLen, disabledSet) {
  if (!disabledSet || disabledSet.size === 0) return generatePrompt(promptLen);
  const lengths = [...new Set([promptLen, promptLen - 1, 2])].filter(l => l >= 2);
  for (const len of lengths) {
    const { counts, legalWords } = _sabotageCounts(disabledSet, len);
    if (legalWords === 0) continue;
    const { pool } = _sabotageFloor(counts);
    if (pool.length) return pool[Math.floor(Math.random() * pool.length)];
  }
  return generatePrompt(promptLen);
}

/**
 * A valid dictionary word containing `prompt`, for the informational
 * "e.g. WORD" flash after a timeout. Random probes give an unbiased pick for
 * common substrings; rare ones fall back to a capped scan. Words already used
 * this game are skipped when possible.
 */
function exampleWordFor(prompt, usedWords) {
  const pool = wordsByMinLen[2]; // effectively the whole dictionary, as an array
  for (let i = 0; i < 1500; i++) {
    const w = pool[(Math.random() * pool.length) | 0];
    if (w.length >= 3 && w.includes(prompt) && !(usedWords && usedWords.has(w))) return w;
  }
  const matches = [];
  for (const w of pool) {
    if (w.length < 3 || !w.includes(prompt)) continue;
    if (usedWords && usedWords.has(w)) continue;
    matches.push(w);
    if (matches.length >= 400) break;
  }
  return matches.length ? matches[(Math.random() * matches.length) | 0] : null;
}

/**
 * Validates a word submission against the current prompt and used-word set.
 * Does NOT modify usedWords - caller adds the word after a successful play.
 *
 * Returns { valid: true } or { valid: false, reason: "..." }.
 */
function isValidWord(word, prompt, usedWords) {
  const w = word.trim().toLowerCase();
  if (!w.includes(prompt)) {
    return { valid: false, reason: `Word must contain "${prompt}".` };
  }
  if (!validWords.has(w)) {
    return { valid: false, reason: `"${w}" is not in the dictionary.` };
  }
  if (w.length < 3) {
    return { valid: false, reason: 'Word must be at least 3 letters long.' };
  }
  if (usedWords.has(w)) {
    return { valid: false, reason: `"${w}" has already been used.` };
  }
  return { valid: true };
}

module.exports = {
  validWords,
  wordsByMinLen,
  substringCounts,
  playablePrompts,
  generatePrompt,
  generateSabotagePrompt,
  sabotageLegalStats,
  generatePracticePrompt,
  solutionCount,
  killerAnswersFor,
  exampleWordFor,
  isValidWord,
  getWordTier,
  getWordScore,
  rarityScore,
  TIER_NAMES,
  generateDailyPrompts,
  letterBaseline,
};

// TEMP Batch 35: remove after review. Verify sabotageLegalStats at promptLen 3
// under the new floor cascade [25, 10, 5, 3, 1].
{
  const cases = [
    { label: '(none)', letters: [] },
    { label: 'j,a,z', letters: ['j', 'a', 'z'] },
    { label: 'q,u,i,x,o,t,c', letters: ['q', 'u', 'i', 'x', 'o', 't', 'c'] },
    { label: 'p,e,r,s,i,c,a,o,u', letters: ['p', 'e', 'r', 's', 'i', 'c', 'a', 'o', 'u'] },
    { label: 'f,l,o,c,i,n,a,u,h,p,t', letters: ['f', 'l', 'o', 'c', 'i', 'n', 'a', 'u', 'h', 'p', 't'] },
  ];
  const expected = {
    '(none)': { legalWords: 273087, richPrompts: 4377, floor: 25 },
    'j,a,z': { legalWords: 115548, richPrompts: 2651, floor: 25 },
    'q,u,i,x,o,t,c': { legalWords: 15859, richPrompts: 627, floor: 25 },
    'p,e,r,s,i,c,a,o,u': { legalWords: 28, richPrompts: 3, floor: 3 },
    'f,l,o,c,i,n,a,u,h,p,t': { legalWords: 1049, richPrompts: 47, floor: 25 },
  };
  for (const c of cases) {
    const s = sabotageLegalStats(new Set(c.letters), 3);
    const e = expected[c.label];
    const okr = s.legalWords === e.legalWords && s.richPrompts === e.richPrompts && s.floor === e.floor;
    console.log(`TEMP Batch 35 sabotageLegalStats[${c.label}] legalWords=${s.legalWords} richPrompts=${s.richPrompts} floor=${s.floor} ${okr ? 'OK' : 'MISMATCH expected ' + JSON.stringify(e)}`);
  }
}
