const fs = require('fs');
const path = require('path');

const MIN_WORDS = 5;

// ── Load words ──────────────────────────────────────────────────────────────
const raw = fs.readFileSync(path.join(__dirname, 'data', 'dictionary.txt'), 'utf8');
const validWords = new Set(
  raw.split('\n').map(w => w.trim()).filter(w => w.length > 0)
);

// ── Build prompt source pools ───────────────────────────────────────────────
// Prompts are generated by picking a random dictionary word and slicing a
// random substring of the requested length out of it. This guarantees every
// prompt is solvable (the source word itself is a valid answer) and naturally
// weights prompts toward letter combos that occur in many words.
//
// wordsByMinLen[len] = array of words at least `len` characters long, so a
// substring of that length can always be cut from a randomly chosen word.
const wordsByMinLen = { 2: [], 3: [], 4: [] };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length >= len) wordsByMinLen[len].push(word);
  }
}

// Kept for diagnostics / backward compatibility: count of distinct words that
// contain each substring, and the substrings appearing in >= MIN_WORDS words.
const substringCounts = { 2: new Map(), 3: new Map(), 4: new Map() };
for (const word of validWords) {
  for (const len of [2, 3, 4]) {
    if (word.length < len) continue;
    const seen = new Set();
    for (let i = 0; i <= word.length - len; i++) {
      const sub = word.slice(i, i + len);
      if (!seen.has(sub)) {
        seen.add(sub);
        substringCounts[len].set(sub, (substringCounts[len].get(sub) || 0) + 1);
      }
    }
  }
}

const playablePrompts = { 2: [], 3: [], 4: [] };
for (const len of [2, 3, 4]) {
  for (const [sub, count] of substringCounts[len]) {
    if (count >= MIN_WORDS) playablePrompts[len].push(sub);
  }
}

// ── Word rarity tiers (Feature 5) ────────────────────────────────────────────
// Score every word by length + average rarity of its 3-letter substrings (rare
// clusters score higher), then bucket by percentile: COMMON (bottom 60%),
// UNCOMMON (next 25%), RARE (next 12%), LEGENDARY (top 3%).
const TIER_NAMES = ['COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY'];
const wordTier = new Map();
(function computeTiers() {
  const total = validWords.size;
  const scored = new Array(total);
  let i = 0;
  for (const word of validWords) {
    let score = word.length;        // longer words skew rarer
    let boost = 0, n = 0;
    const L = word.length;
    for (let j = 0; j + 3 <= L; j++) {
      const c = substringCounts[3].get(word.slice(j, j + 3)) || 1;
      boost += Math.log10((total + 1) / (c + 1)); // high when the cluster is rare
      n++;
    }
    if (n) score += (boost / n) * 2.5;
    scored[i++] = [word, score];
  }
  scored.sort((a, b) => a[1] - b[1]);
  const c1 = Math.floor(total * 0.60);
  const c2 = Math.floor(total * 0.85);
  const c3 = Math.floor(total * 0.97);
  for (let k = 0; k < total; k++) {
    const tier = k < c1 ? 'COMMON' : k < c2 ? 'UNCOMMON' : k < c3 ? 'RARE' : 'LEGENDARY';
    wordTier.set(scored[k][0], tier);
  }
})();

/**
 * Returns the rarity tier ('COMMON' | 'UNCOMMON' | 'RARE' | 'LEGENDARY') of a
 * word. Unknown words (e.g. themed-only words) default to COMMON.
 */
function getWordTier(word) {
  return wordTier.get(String(word).trim().toLowerCase()) || 'COMMON';
}

// ── Daily challenge prompt pools (Feature 8) ─────────────────────────────────
// Bucket each length's playable substrings by how many distinct words contain
// them. High count = many solutions = easy; low count = few solutions = hard
// (but still solvable, since the pool is the >= MIN_WORDS playable set).
function bucketByCount(len) {
  const arr = playablePrompts[len].map(s => [s, substringCounts[len].get(s) || 0]);
  arr.sort((a, b) => a[1] - b[1]); // ascending: rare → common
  const n = arr.length;
  const third = Math.floor(n / 3);
  return {
    rare:   arr.slice(0, third).map(x => x[0]),
    mid:    arr.slice(third, 2 * third).map(x => x[0]),
    common: arr.slice(2 * third).map(x => x[0]),
  };
}
const _b2 = bucketByCount(2), _b3 = bucketByCount(3), _b4 = bucketByCount(4);
const dailyPools = {
  common2: _b2.common,            // easy: common 2-letter clusters
  mid3:    _b3.mid,               // medium: mid-rarity 3-letter clusters
  rare34:  _b3.rare.concat(_b4.rare), // hard: rare 3/4-letter clusters
};

// Deterministic PRNG so a given day yields the same sequence for everyone.
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Builds the 30-prompt daily gauntlet for a given YYYYMMDD integer. Difficulty
 * ramps: 1-10 easy 2-letter, 11-20 mid 3-letter, 21-30 rare 3/4-letter.
 */
function generateDailyPrompts(dateInt) {
  const rng = mulberry32(dateInt);
  const used = new Set();
  const draw = (pool) => {
    let p, guard = 0;
    do { p = pool[Math.floor(rng() * pool.length)]; guard++; } while (used.has(p) && guard < 60);
    used.add(p);
    return p;
  };
  const out = [];
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.common2));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.mid3));
  for (let i = 0; i < 10; i++) out.push(draw(dailyPools.rare34));
  return out;
}

// ── Exports ─────────────────────────────────────────────────────────────────

/**
 * Returns a random prompt of the given length (2, 3, or 4) by choosing a random
 * dictionary word and slicing a random substring of that length out of it.
 */
function generatePrompt(length) {
  const pool = wordsByMinLen[length];
  const word = pool[Math.floor(Math.random() * pool.length)];
  const start = Math.floor(Math.random() * (word.length - length + 1));
  return word.slice(start, start + length);
}

/**
 * Validates a word submission against the current prompt and used-word set.
 * Does NOT modify usedWords — caller adds the word after a successful play.
 *
 * Returns { valid: true } or { valid: false, reason: "..." }.
 */
function isValidWord(word, prompt, usedWords) {
  const w = word.trim().toLowerCase();
  if (!w.includes(prompt)) {
    return { valid: false, reason: `Word must contain "${prompt}".` };
  }
  if (!validWords.has(w)) {
    return { valid: false, reason: `"${w}" is not in the dictionary.` };
  }
  if (w.length < 3) {
    return { valid: false, reason: 'Word must be at least 3 letters long.' };
  }
  if (usedWords.has(w)) {
    return { valid: false, reason: `"${w}" has already been used.` };
  }
  return { valid: true };
}

module.exports = {
  validWords,
  wordsByMinLen,
  substringCounts,
  playablePrompts,
  generatePrompt,
  isValidWord,
  getWordTier,
  TIER_NAMES,
  generateDailyPrompts,
};
